# Ruff configuration file
# See https://docs.astral.sh/ruff/configuration/

target-version = "py311"
line-length = 88
indent-width = 4

[lint]
# Enable specific rule sets
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
    "N",   # pep8-naming
    "C4",  # flake8-comprehensions
    "ICN", # flake8-import-conventions
    "PIE", # flake8-pie
    "T20", # flake8-print
    "PYI", # flake8-pyi
    "PT",  # flake8-pytest-style
    "Q",   # flake8-quotes
    "RSE", # flake8-raise
    "RET", # flake8-return
    "S",   # flake8-bandit
    "TID", # flake8-tidy-imports
    "TCH", # flake8-type-checking
    "ARG", # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "ERA", # eradicate
    "PD",  # pandas-vet
    "PGH", # pygrep-hooks
    "PL",  # Pylint
    "TRY", # tryceratops
    "NPY", # NumPy-specific rules
    "RUF", # Ruff-specific rules
]

ignore = [
    "E501",   # line-too-long (handled by formatter)
    "S101",   # assert-used (pytest uses assertions)
    "S311",   # suspicious-non-cryptographic-random-usage
    "PLR0913", # too-many-arguments
    "PLR0915", # too-many-statements
    "TRY003",  # raise-vanilla-args
    "PD901",   # pandas-df-variable-name
]

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"__init__.py" = ["F401", "E402"]
"tests/**/*.py" = [
    "S101",    # asserts allowed in tests
    "ARG",     # unused function args -> fixtures nevertheless are functionally relevant
    "FBT",     # don't care about booleans as positional arguments in tests
    "PLR2004", # Magic value used in comparison, consider replacing with a constant variable
    "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
]

[lint.isort]
known-first-party = ["app", "etl", "expectations"]
force-single-line = true

[format]
# Use double quotes for strings
quote-style = "double"

# Use spaces for indentation
indent-style = "space"

# Respect magic trailing commas
skip-magic-trailing-comma = false

# Automatically detect line endings
line-ending = "auto"